#
# Makefile --Build rules for libtwin, the text window library.
#
language = c
C_SRC = twidget.c twin.c xterminator.c
H_SRC = twidget.h twin.h xterminator.h

include makeshift.mk library.mk

install: install-lib
uninstall: uninstall-lib
